# Generated by Django 4.0.2 on 2022-03-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=0, max_length=100)),
                ('year', models.CharField(default=0, max_length=10)),
                ('month', models.CharField(default=0, max_length=10)),
                ('gangnam', models.IntegerField(default=0)),
                ('songpa', models.IntegerField(default=0)),
                ('gangdong', models.IntegerField(default=0)),
                ('sdm', models.IntegerField(default=0)),
                ('yangcheon', models.IntegerField(default=0)),
                ('seocho', models.IntegerField(default=0)),
                ('junggu', models.IntegerField(default=0)),
                ('seongdong', models.IntegerField(default=0)),
                ('yongsan', models.IntegerField(default=0)),
                ('guro', models.IntegerField(default=0)),
                ('dongjak', models.IntegerField(default=0)),
                ('gwangjin', models.IntegerField(default=0)),
                ('ddm', models.IntegerField(default=0)),
                ('ydpa', models.IntegerField(default=0)),
                ('seongbuk', models.IntegerField(default=0)),
                ('gangbuk', models.IntegerField(default=0)),
                ('gangseo', models.IntegerField(default=0)),
                ('geumcheon', models.IntegerField(default=0)),
                ('gwanak', models.IntegerField(default=0)),
                ('mapo', models.IntegerField(default=0)),
                ('dobong', models.IntegerField(default=0)),
                ('ep', models.IntegerField(default=0)),
                ('jungnang', models.IntegerField(default=0)),
                ('jongno', models.IntegerField(default=0)),
                ('nowon', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patient2',
            fields=[
                ('ward', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('month1', models.IntegerField(default=0)),
                ('month2', models.IntegerField(default=0)),
                ('month3', models.IntegerField(default=0)),
                ('month4', models.IntegerField(default=0)),
                ('month5', models.IntegerField(default=0)),
                ('month6', models.IntegerField(default=0)),
                ('month7', models.IntegerField(default=0)),
                ('month8', models.IntegerField(default=0)),
                ('month9', models.IntegerField(default=0)),
                ('month10', models.IntegerField(default=0)),
                ('month11', models.IntegerField(default=0)),
                ('month12', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('location', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('month', models.IntegerField(default=0)),
                ('month7', models.IntegerField(default=0)),
                ('month8', models.IntegerField(default=0)),
                ('month9', models.IntegerField(default=0)),
                ('month10', models.IntegerField(default=0)),
            ],
        ),
    ]
