# Generated by Django 4.0.2 on 2022-03-03 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_no', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('b_title', models.CharField(max_length=100)),
                ('b_content', models.TextField()),
                ('b_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 21, 42, 45, 612087))),
                ('b_hit', models.IntegerField(default=1)),
                ('b_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Commnet',
            fields=[
                ('c_no', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('c_content', models.TextField()),
                ('c_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 21, 42, 45, 612087))),
                ('c_pw', models.CharField(blank=True, max_length=10)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board1.board')),
            ],
        ),
    ]
