# Generated by Django 4.0.2 on 2022-03-03 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board1', '0002_comment_alter_board_b_date_delete_commnet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 23, 2, 14, 708808)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 23, 2, 14, 708808)),
        ),
    ]
