# Generated by Django 4.0.2 on 2022-03-03 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board1', '0003_alter_board_b_date_alter_comment_c_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 23, 21, 23, 49931)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 23, 21, 23, 49931)),
        ),
    ]
