# Generated by Django 4.0.2 on 2022-03-04 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board1', '0007_alter_board_b_date_alter_comment_c_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 4, 15, 25, 36, 308395)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 4, 15, 25, 36, 309392)),
        ),
    ]
